default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host:  <%= ENV.fetch("MYSQL_HOST") { "localhost" }  %>
  reconnect: false
  timeout: 5000
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: development


test:
  <<: *default
  database: test


production:
  <<: *default
  database: production
  username: api
  password: <%= ENV["MKPLA_APPS_DATABASE_PASSWORD"] %>